////////////////////////////////////////////////////////////
// Name : IEnumOLEVERB.odl
// Author : Paul R. Wilde
// Created : 23rd April 1999
/////////////////////////////////////////////////////////////
// Copyright © Paul R. Wilde 1999. All Rights Reserved.
/////////////////////////////////////////////////////////////
// Bug reports, suggestions & comments should be emailed to :
// prw.exponential@dial.pipex.com
/////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////
// Revision history
/////////////////////////////////////////////////////////////
// 23/04/99
// Initial development
/////////////////////////////////////////////////////////////


[
    	uuid(00000104-0000-0000-C000-000000000046),
	odl
]

interface IEnumOLEVERB : IUnknown
{
    	typedef IEnumOLEVERB *LPENUMOLEVERB;

    	HRESULT Next
	(
        	[in] ULONG celt,
        	[in, out] LPOLEVERB rgelt,
        	[in, out] ULONG *pceltFetched
	);

    	HRESULT Skip
	(
        	[in] ULONG celt
	);

    	HRESULT Reset
	(
	);

    	HRESULT Clone
	(
        	[in, out] IEnumOLEVERB **ppenum
	);
}

